= Asciidoctor Tabs Changelog
:url-repo: https://github.com/asciidoctor/asciidoctor-tabs

This document provides a curated view of the changes to Asciidoctor Tabs per release.
For a detailed view of what has changed, refer to the {url-repo}/commits/main[commit history] on GitHub.

== 1.0.0-alpha.9 (2022-12-07) - @mojavelinux

=== Changed

* Assign `tab` role to each item in tab list
* Apply border and padding to tab pane element instead of its parent
* Remove fixed height on tab element; using padding instead
* Use more subtle color scheme for border and background colors on tabs

=== Fixed

* Configure overflow content in tab panel to scroll horizontally
* Set background on tabs properly so background does not bleed through

=== Details

{url-repo}/releases/tag/v1.0.0-alpha.9[git tag] | {url-repo}/compare/v1.0.0-alpha.8\...v1.0.0-alpha.9[full diff]

== 1.0.0-alpha.8 (2022-11-30) - @mojavelinux

=== Fixed

* Sync tab selection on hash change (#32)
* Lock position of content when synchronizing tab selection (#34)
* Remove bottom margin from last block in tab pane for the most common cases

=== Details

{url-repo}/releases/tag/v1.0.0-alpha.8[git tag] | {url-repo}/compare/v1.0.0-alpha.7\...v1.0.0-alpha.8[full diff]

== 1.0.0-alpha.7 (2022-11-28) - @mojavelinux

=== Added

* In tabs script, add `tab` class to tab element
* Sync tab selection across tabs blocks if `sync` option is set on tabs block or `tabs-sync-option` attribute is set on document (#28)
* Delist tabs block from sync if `nosync` option is set on block (#28)

=== Changed

* When inline anchor is used for tab ID, promote value of id attribute to id attribute on tab and remove anchor

=== Fixed

* Apply normal substitutions to principal text (first paragraph) of tab's content (#29)

=== Details

{url-repo}/releases/tag/v1.0.0-alpha.7[git tag] | {url-repo}/compare/v1.0.0-alpha.6\...v1.0.0-alpha.7[full diff]

== 1.0.0-alpha.6 (2022-11-16) - @mojavelinux

=== Added

* Honor title on tabs block; apply normal subs to it (#26)
* Clear location hash (URL fragment) when a tab is clicked (#24)
* Register ref for each tab so its ID can be used as target of xref (#24)
* Activate tab when selected from an internal xref (#24)

=== Fixed

* Decode fragment from URL so it can be matched against tab ID (#27)

=== Details

{url-repo}/releases/tag/v1.0.0-alpha.6[git tag] | {url-repo}/compare/v1.0.0-alpha.5\...v1.0.0-alpha.6[full diff]

== 1.0.0-alpha.5 (2022-10-23) - @mojavelinux

=== Added

* Link to stylesheet (style) and script (behavior) if `linkcss` attribute is set on document (#7)
* Honor safe mode settings (don't read files if safe mode is secure) (#7)

=== Changed

* Rename Docinfo::Styles class to Docinfo::Style (#22)
* Add smoke test for npm package (#19)

=== Fixed

* Prevent dlist ref from being registered again to avoid warning when filetype is not html (#21)
* Restore missing default style and behavior in JavaScript version by mapping data dir to dist folder in npm package (#18)

=== Details

{url-repo}/releases/tag/v1.0.0-alpha.5[git tag] | {url-repo}/compare/v1.0.0-alpha.4\...v1.0.0-alpha.5[full diff]

== 1.0.0-alpha.4 (2022-10-08) - @mojavelinux

=== Added

* Define exports for behavior (tabs.js) and style (tabs.css) in npm package

=== Changed

* Use value of `idseparator` attribute in front of tabset number in auto-generated ID (#16)
* Add aliases for `Block` and `Docinfo` classes to `Extensions` class; remove workaround in js module
* Move `margin-bottom` style to tabset element
* Move behavior (tabs.js) and style (tabs.css) to dist folder in npm package

=== Fixed

* Increase specificity of sibling selector for tab to work with Antora default UI

=== Details

{url-repo}/releases/tag/v1.0.0-alpha.4[git tag] | {url-repo}/compare/v1.0.0-alpha.3\...v1.0.0-alpha.4[full diff]

== 1.0.0-alpha.3 (2022-10-05) - @mojavelinux

=== Added

* Provide fallback behavior for non-HTML backends (filetype is not html) (#4)
* Support multiple tab labels (terms) for the same content (description) (#8)
* Allow alternate stylesheet for tabs to be specified using `tabs-stylesheet` attribute (#6)

=== Changed

* Assign ID directly to tab (list item) node (instead of using inline anchor) if backend supports it (#11)

=== Fixed

* Preserve text of dlist item for tab if item has both text and blocks (#13)
* Create empty pane instead of crashing if dlist item has term only / no description

=== Details

{url-repo}/releases/tag/v1.0.0-alpha.3[git tag] | {url-repo}/compare/v1.0.0-alpha.2\...v1.0.0-alpha.3[full diff]

== 1.0.0-alpha.2 (2022-10-03) - @mojavelinux

=== Added

* Transpile `Asciidoctor::Tabs::Extensions` class for npm package

=== Changed

* Rename `idx-tabset` counter to `tabset-number` to be consistent with built-in counter names
* Don't register docinfo extensions if converter is producing embedded output
* Update `register` and `unregister` on `Asciidoctor::Tabs::Extensions` to accept a registry argument
* Delegate registration of extension in npm package to `Asciidoctor::Tabs::Extensions.register` method
* Allow `Extensions` class to be required from `@asciidoctor/tabs/extensions` in Node.js; attach `Block` and `Docinfo` classes

=== Fixed

* Honor explicit ID on tabs block and use it as ID prefix for tabs
* Register reference for tabset in document catalog
* Autogenerate IDs for tabsets and tabs in a manner consistent with section ID generation (#2)
* Fix context value on pass blocks created by extension

=== Details

{url-repo}/releases/tag/v1.0.0-alpha.2[git tag] | {url-repo}/compare/v1.0.0-alpha.1\...v1.0.0-alpha.2[full diff]

== 1.0.0-alpha.1 (2022-10-01) - @mojavelinux

_Initial prerelease._

=== Details

{url-repo}/releases/tag/v1.0.0-alpha.1[git tag]
