= Asciidoctor Tabs Changelog
:url-repo: https://github.com/asciidoctor/asciidoctor-tabs

This document provides a curated view of the changes to Asciidoctor Tabs per release.
For a detailed view of what has changed, refer to the {url-repo}/commits/main[commit history] on GitHub.

== Unreleased

=== Added

* Provide fallback behavior for non-HTML backends (filetype is not html) (#4)

=== Fixed

* Create empty pane instead of crashing if dlist item has term only / no description

== 1.0.0-alpha.2 (2022-10-03) - @mojavelinux

=== Added

* Transpile `Asciidoctor::Tabs::Extensions` class for npm package

=== Changed

* Rename `idx-tabset` counter to `tabset-number` to be consistent with built-in counter names
* Don't register docinfo extensions if converter is producing embedded output
* Update `register` and `unregister` on `Asciidoctor::Tabs::Extensions` to accept a registry argument
* Delegate registration of extension in npm package to `Asciidoctor::Tabs::Extensions.register` method
* Allow `Extensions` class to be required from `@asciidoctor/tabs/extensions` in Node.js; attach `Block` and `Docinfo` classes

=== Fixed

* Honor explicit ID on tabs block and use it as ID prefix for tabs
* Autogenerate IDs for tabsets and tabs in a manner consistent with section ID generation (#2)

=== Details

{url-repo}/releases/tag/v1.0.0-alpha.2[git tag] | {url-repo}/compare/v1.0.0-alpha.1\...v1.0.0-alpha.2[full diff]

== 1.0.0-alpha.1 (2022-10-01) - @mojavelinux

_Initial release._

=== Details

{url-repo}/releases/tag/v1.0.0-alpha.1[git tag]
