= Asciidoctor Tabs
Dan Allen <https://github.com/mojavelinux[@mojavelinux]>
v1.0.0-alpha.1, 2022-10-01
:idprefix:
:idseparator: -

An Asciidoctor extension that adds a tabs block to the AsciiDoc syntax.
Each set of tabs (a "tabset") is constructed from a dlist enclosed in an example block marked with the tabs style.
This extension is only designed to be used with the `html` backend.

== Install

=== Using gem command

 $ gem install --prerelease asciidoctor-tabs

=== Using Bundler

Create a [.path]_Gemfile_ in your project:

.Gemfile
[,ruby]
----
source 'https://rubygems.org'

gem 'asciidoctor-tabs'

# or use the code directlly from GitHub
# gem 'asciidoctor-tabs', github: 'asciidoctor/asciidoctor-pdf'
----

Then configure Bundler to install gems locally (optional):

 $ bundle config --local path .bundle/gems

Then use Bundler to install the gem:

 $ bundle

== Syntax

A tabset is defined using a dlist enclosed in an example block marked with the tabs style.
Each item in the dlist becomes a separate tab.
The term in the dlist item is used as the tab's label.
The description in the dlist item is used for the contents of the tab.
The contents can be defined as primary text, attached blocks, or blocks enclosed in an attached open block.
If the blocks are enclosed in an attached open block, the open block enclosure itself will be discarded.

.document-with-tabs.adoc
[,asciidoc]
----
[tabs]
====
Tab A:: Contents of tab A.

Tab B::
+
Contents of tab B.

Tab C::
+
--
Contents of tab C.

Contains more than one block.
--
====
----

== Usage

 $ asciidoctor -r asciidoctor-tabs document-with-tabs.adoc

== Authors

Asciidoctor Tabs was written by Dan Allen of OpenDevise Inc. and contributed to the Asciidoctor project.

== Copyright and License

Copyright (C) 2018-present Dan Allen (OpenDevise Inc.) and the individual contributors to this project.
Use of this software is granted under the terms of the MIT License.

See the link:LICENSE[LICENSE] for the full license text.

== Trademarks

AsciiDoc(R) is a trademark of the Eclipse Foundation, Inc.
