= Asciidoctor Tabs
Dan Allen <https://github.com/mojavelinux[@mojavelinux]>
v1.0.0-alpha.4, 2022-10-08
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github[]
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]

An Asciidoctor extension that adds a tabs block to the AsciiDoc syntax.

NOTE: This extension is intended to be used with HTML backends (e.g., `html5`).
For all other backends (i.e., the filetype is not html), the custom block enclosure will be taken away and its contents converted normally.

TIP: This extension is also published as an npm package named `@asciidoctor/tabs` for use with Asciidoctor.js (and thus Antora).

== Overview

Each set of tabs (a "`tabset`") is constructed from a description list (dlist) enclosed in an example block marked with the tabs style (i.e., `[tab]`).
The tabbed interface that this block produces can help to organize information by code language, operating system, or product variant.

The benefit of organizing information in this way is that it condenses the use of vertical space by only showing what is relevant to the reader (and thus hiding information that's irrelevant or redundant).
The result is that readers enjoy a better user experience when reading your documentation.

== Install

=== Using gem command

 $ gem install --prerelease asciidoctor-tabs

=== Using Bundler

Create a [.path]_Gemfile_ in your project:

.Gemfile
[,ruby]
----
source 'https://rubygems.org'

gem 'asciidoctor-tabs'

# or use the code directlly from GitHub
# gem 'asciidoctor-tabs', github: 'asciidoctor/asciidoctor-tabs'
----

Then configure Bundler to install gems locally (optional):

 $ bundle config --local path .bundle/gems

Then use Bundler to install the gem:

 $ bundle

== Syntax

A tabset is defined using a description list (dlist) enclosed in an example block marked with the tabs style.

.document-with-tabs.adoc
[,asciidoc]
----
[tabs]
====
Tab A:: Contents of tab A.

Tab B::
+
Contents of tab B.

Tab C::
+
--
Contents of tab C.

Contains more than one block.
--
====
----

The tabbed content is modeled as a dlist.
Each item in the dlist becomes a separate tab.
The term is used as the tab's label and the description is used as the tab's contents.
The contents can be defined as primary text, attached blocks, or both.
If the attached blocks are themselves enclosed in a single open block, the open block enclosure itself will be discarded.

You may decide to extend the block delimiter length instead of using the typical 4 characters to avoid conflicts with any example blocks inside the tab block (or just as a manner of style).

[,asciidoc]
----
[tabs]
======
Tab A::
+
====
Example block in Tab A.
====

Tab B:: Just text.
======
----

== Usage

=== CLI

 $ asciidoctor -r asciidoctor-tabs document-with-tabs.adoc

You can specify an alternate stylesheet for tabs using the `tabs-stylesheet` document attribute.
The value of this attribute is handled in the same way as the built-in `stylesheet` document attribute.
A relative path is resolved starting from the value of the `stylesdir` document attribute, which defaults to the directory of the document.

 $ asciidoctor -r asciidoctor-tabs -a tabs-stylesheet=my-tabs.css document-with-tabs.adoc

=== API

There are two ways to use the extension with the Asciidoctor API.
In either case, you must require the Asciidoctor gem (`asciidoctor`) before requiring this one.

You can require `asciidoctor/tabs` to register the extension as a global extension, just like with the CLI.

[,js]
----
require 'asciidoctor'
require 'asciidoctor/tabs'

Asciidoctor.convert_file 'document-with-tabs.adoc', safe: :safe
----

Or you can pass a registry instance to the `Extensions.register` method to register the extension with a scoped registry.

[,js]
----
require 'asciidoctor'
require 'asciidoctor/tabs/extensions'

registry = Asciidoctor::Extensions.create
Asciidoctor::Tabs::Extensions.register registry

Asciidoctor.convert_file 'document-with-tabs.adoc', extension_registry: registry, safe: :safe
----

If you're not using other scoped extensions, you can pass in the extensions group without creating a registry instance:

[,js]
----
Asciidoctor.convert_file 'document-with-tabs.adoc', extensions: Asciidoctor::Tabs::Extensions.group, safe: :safe
----

== Authors

Asciidoctor Tabs was written by Dan Allen of OpenDevise Inc. and contributed to the Asciidoctor project.

== Copyright and License

Copyright (C) 2018-present Dan Allen (OpenDevise Inc.) and the individual contributors to this project.
Use of this software is granted under the terms of the MIT License.

See the link:LICENSE[LICENSE] for the full license text.

== Trademarks

AsciiDoc(R) is a trademark of the Eclipse Foundation, Inc.
